<!--page d'accueil de l'admin-->

	    <fieldset> 
            <legend><h2>Gestion Admin</h2></legend>
            <!--l'admin peut pour le moment supprimer les commentaires, les posts et les users-->
    		<form method="post">
    		    <label for="coms">Gestion des commentaires : </label>
    		    <button><a title ="modifier commentaires" href="../public/index.php?action=editComs" name ="modifcom">Modifier</a></button>
    		    <label for="posts">Gestion des posts : </label>
    		    <button><a title ="modifier posts" href="../public/index.php?action=editPosts" name ="modifpost">Modifier</a></button>
    		    <label for="users">Gestion des utilisateurs : </label>
    		    <button><a title ="modifier users" href="../public/index.php?action=editUsers" name ="modifuser">Modifier</a></button>
    		</form>
    	</fieldset>
	