
        <fieldset>  
            <legend><h2>Poster un commentaire.</h2></legend>
                               
        		<form method="post">
        		    <label for="pseudo">Pseudo : </label>
        			<input type="text" name="pseudo" placeholder="Votre pseudo" required/>
        			
        			<label for="com">Commentaire :</label>
        			<input type="text" name="comment" placeholder="Écrivez votre commentaire" required/>
        			
        			<button class="submit" type="submit" name="commentaire">Laisser un commentaire</button>
        		</form>
        </fieldset>
    